package com.example.dopaminecut2.logic.shortform

import org.junit.Assert.assertArrayEquals
import org.junit.Test

class AntialiasedBilinearResizeTest {
    @Test
    fun `downscale matches Pillow bilinear golden pixels including image edges`() {
        val width = 13
        val height = 19
        val input = IntArray(width * height) { index ->
            val x = index % width
            val y = index / width
            (255 shl 24) or (((x * 37 + y * 13) % 256) shl 16) or
                (((x * 11 + y * 53) % 256) shl 8) or ((x * 71 + y * 7) % 256)
        }
        // Generated by Pillow Image.Resampling.BILINEAR from the same 13 x 19 RGB image.
        val expected = intArrayOf(-12688040, -7113850, -7765104, -11040891, -5469087, -9800851, -5277812, -10651263, -8160893, -4684935, -6583685, -6978199, -10782311, -5738113, -9273746, -5404011, -10714497, -8024196, -6849399, -11830413, -8354927, -11236479, -5794964, -10122335, -9924725)
        assertArrayEquals(expected, AntialiasedBilinearResize.resize(input, width, height, 5))
    }

    @Test
    fun `constant colors stay constant when upscaling and downscaling`() {
        val color = 0xff2850a0.toInt()
        for (size in listOf(2, 8)) {
            assertArrayEquals(IntArray(size * size) { color },
                AntialiasedBilinearResize.resize(IntArray(16) { color }, 4, 4, size))
        }
    }
}
